Repository boxmetrics/boxmetrics-agent, pull requests merged in 2019-04, with the labels that each got.

#1 Add basic readme docs
  README.md
  build/package/.gitkeep
  cmd/boxagent/main.go
Labels: docs

#2 Add `Makefile`
  .gitignore
  Makefile
  README.md
  configs/.gitkeep
  configs/server.csr.cnf
  configs/v3.ext
Labels: enhancement

#7 add ci-cd
  .gitignore
  Dockerfile
  JenkinsFile
  Makefile
Labels: ci-cd

#9 Clean repository
  Dockerfile
  JenkinsFile
  Makefile
  README.md
  build/ci/.gitkeep
  build/ci/JenkinsFile
  certificates/.gitkeep
  cmd/boxagent/main.go
Labels: clean
